controllers:
    resource: ../src/Controller/
    type: attribute


welcome:
    path: /
    controller: App\Controller\WelcomeController::index


product_create:
    path: /product/create
    controller: App\Controller\ProductController::create




product_index:
    path: /product
    controller: App\Controller\ProductController::index

