controllers:
    resource: ../src/Controller/
    type: attribute


welcome:
    path: /
    controller: App\Controller\WelcomeController::index


product_create:
    path: /product/create
    controller: App\Controller\ProductController::create




product_index:
    path: /product
    controller: App\Controller\ProductController::index

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register


app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

    # config/routes.yaml

